from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol

from matey.models import (
    ArtifactDelete,
    ArtifactWrite,
    CmdResult,
    Engine,
    EnginePolicy,
    PreparedSql,
    ScratchHandle,
    SqlComparison,
    SqlSource,
    TargetKey,
    WorktreeChange,
)


class IProcessRunner(Protocol):
    def run(self, argv: tuple[str, ...], cwd: Path | None = None) -> CmdResult: ...


class IFileSystem(Protocol):
    def read_bytes(self, path: Path) -> bytes: ...
    def read_text(self, path: Path) -> str: ...
    def write_bytes_atomic(self, path: Path, data: bytes) -> None: ...
    def write_text_atomic(self, path: Path, data: str) -> None: ...
    def exists(self, path: Path) -> bool: ...
    def mkdir(self, path: Path, parents: bool = False) -> None: ...
    def list_files(self, path: Path) -> tuple[Path, ...]: ...


class IEnvProvider(Protocol):
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def require(self, key: str) -> str: ...


class IGitRepo(Protocol):
    def repo_root(self) -> Path: ...
    def head_commit(self) -> str: ...
    def resolve_ref(self, ref: str) -> str: ...
    def merge_base(self, left_ref: str, right_ref: str) -> str: ...
    def read_blob_bytes(self, commit: str, rel_path: Path) -> bytes | None: ...
    def list_tree_paths(self, commit: str, rel_dir: Path) -> tuple[Path, ...]: ...
    def has_local_changes(self, *, rel_paths: tuple[Path, ...]) -> bool: ...
    def list_local_changes(self, *, rel_paths: tuple[Path, ...]) -> tuple[WorktreeChange, ...]: ...


class ISqlPipeline(Protocol):
    def prepare(self, *, engine: Engine, source: SqlSource) -> PreparedSql: ...
    def compare(self, *, engine: Engine, expected: SqlSource, actual: SqlSource) -> SqlComparison: ...


class IEnginePolicyRegistry(Protocol):
    def get(self, engine: Engine) -> EnginePolicy: ...


class IScratchManager(Protocol):
    def prepare(
        self,
        *,
        engine: Engine,
        scratch_name: str,
        purpose: str,
        test_base_url: str | None,
        keep: bool,
    ) -> ScratchHandle: ...

    def cleanup(self, handle: ScratchHandle) -> None: ...


class IDbmateGateway(Protocol):
    def new(self, name: str, migrations_dir: Path) -> CmdResult: ...
    def wait(self, url: str, timeout_seconds: int) -> CmdResult: ...
    def create(self, url: str, migrations_dir: Path) -> CmdResult: ...
    def drop(self, url: str, migrations_dir: Path) -> CmdResult: ...
    def up(self, url: str, migrations_dir: Path, no_dump_schema: bool = True) -> CmdResult: ...
    def migrate(self, url: str, migrations_dir: Path, no_dump_schema: bool = True) -> CmdResult: ...
    def rollback(self, url: str, migrations_dir: Path, steps: int, no_dump_schema: bool = True) -> CmdResult: ...
    def load_schema(
        self,
        url: str,
        schema_path: Path,
        migrations_dir: Path,
        no_dump_schema: bool = True,
    ) -> CmdResult: ...
    def dump(self, url: str, migrations_dir: Path) -> CmdResult: ...
    def status(self, url: str, migrations_dir: Path) -> CmdResult: ...
    def raw(self, argv_suffix: tuple[str, ...], url: str, migrations_dir: Path) -> CmdResult: ...


class IArtifactStore(Protocol):
    def recover_pending(self, *, target_key: TargetKey, target_root: Path) -> None: ...

    def begin(
        self,
        *,
        target_key: TargetKey,
        target_root: Path,
        writes: tuple[ArtifactWrite, ...],
        deletes: tuple[ArtifactDelete, ...],
    ) -> str: ...

    def apply(self, *, txid: str) -> None: ...
    def finalize(self, *, txid: str) -> None: ...


class ICommandScope(Protocol):
    def open(self, *, target_key: TargetKey, target_root: Path) -> AbstractContextManager[None]: ...
