target-version = "py311"
line-length = 100

exclude = [
  ".matey",
  ".pixi",
  ".pytest_cache",
  "__pycache__",
  "build",
  "dist",
  "*.egg-info",
]

[lint]
select = ["E", "F", "I", "UP", "B"]
extend-select = ["RUF", "C4", "SIM", "RET", "PIE", "PERF", "TRY", "PTH", "PLW", "PLR1714", "N"]
ignore = ["E501", "TRY003"]

[lint.isort]
known-first-party = ["matey"]
